services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./static:/usr/share/nginx/html/static
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - .:/app